# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160826_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
