# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='id_com_aerea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voo_com_id', to='website.com_aerea'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='id_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voo_id_destino', to='website.cidade'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='id_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voo_id_origem', to='website.cidade'),
        ),
    ]
