# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160826_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_aerea',
            old_name='nome',
            new_name='name',
        ),
    ]
