# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160830_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_aerea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
