# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160830_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='nome',
            new_name='name',
        ),
    ]
